services:

  eve-embedding:
    container_name: eve-embedding
    hostname: eve-embedding
    image: docker.io/vllm/vllm-openai-cpu:latest-x86_64
    privileged: true
    environment:
      VLLM_DEVICE: cpu
      VLLM_CPU_KVCACHE_SPACE: "1"
      EMBEDDING_DEVICE: cpu
      EMBEDDING_DTYPE: bfloat16
      EMBEDDING_MAX_MODEL_LEN: "2048"
      EMBEDDING_CPU_KVCACHE_SPACE: "1"
    shm_size: 4g
